### ISSUE TITLE
VirtualBox Extension Pack re-distribution is not allowed.

### ISSUE THREAD

**Issue by fabiscafe** [endeavouros-team/repo#4]
From the licensing text you share in the package.
```
3 RESTRICTIONS AND RESERVATION OF RIGHTS.

(1) The Product and copies thereof provided to you under this Agreement
are copyrighted and licensed, not sold, to you by Oracle.

(2) You may not do any of the following: (a) modify any part of the
Product, except to the extent allowed in the documentation accompanying
the Product; (b) rent, lease, lend, re-distribute, or encumber the
Product; (c) remove or alter any proprietary legends or notices contained
in the Product; or (d) decompile, or reverse engineer the Product
(except to the extent permitted by applicable law).
```

Therefore the virtualbox-ext-oracle-*-any.pkg.tar.* shouldn't be in the repos/gitlab.

More: https://www.virtualbox.org/wiki/VirtualBox_PUEL

* https://github.com/endeavouros-team/repo/blob/master/endeavouros/x86_64/virtualbox-ext-oracle-6.1.30-1-any.pkg.tar.zst
* As well as previous version that are still available in the gitlab repo history.

**Comment by manuel-192** [comment]
Thanks, we'll remove the package as soon as possible.
