### ISSUE TITLE
yay package missing fakeroot dependency

### ISSUE THREAD

**Issue by notlet** [endeavouros-team/repo#6]
I added endeavouros repos on a fresh arch linux installation, installed yay, but it crashed due to missing fakeroot binary. Would be nice if fakeroot was added to yay dependencies so it would be installed automatically if not already there. Not sure if it's also needed for other AUR helpers, as I've only used yay.

**Comment by killajoe** [comment]
this is the wrong place to report specific package issue.
Aside from that we are not changing yay PKGBUILD, it is the same as the one from AUR maintained by it's developer: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yay  but still strange that it fails.. is it the same if you are building yay manually from AUR directly?  fakerot is optional for pacman for pacman-contrib .. best would be to check AUR build and report to jguer himself at AUR page.

**Comment by notlet** [comment]
I think this is an issue specifically with distributing yay as a prebuilt binary, as to build it you need base-devel, which fakeroot is a dependency for. So, if you don't build yay and get it as a binary, base-devel is not required, and as a result, fakeroot is not installed.
